include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - enyoi/**
    - firebase_login_migration/**
    - build/**
    - android/**
    - ios/**
    - web/**
    - windows/**
    - macos/**
    - linux/**
